--count the number of orders for each user:--

SELECT
    U.FIRSTNAME,
    U.LASTNAME,
    COUNT(O.ORDERID) AS NUMBEROFORDERS
FROM USERS AS U
LEFT JOIN USERORDERS AS O ON U.USERID = O.USERID
GROUP BY U.FIRSTNAME, U.LASTNAME;
