CREATE TABLE ADVENTUREWORKS2022.SALES.STORENEW (
    STORED_ID INT PRIMARY KEY NOT NULL,
    SALE INT
)

CREATE TABLE ADVENTUREWORKS2022.SALES.VISITS (
    VISIT_ID INT PRIMARY KEY IDENTITY (1, 1),
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    VISITED_AT DATETIME,
    PHONE VARCHAR(20),
    STORED_ID INT NOT NULL,
    FOREIGN KEY (STORED_ID) REFERENCES SALES.STORENEW (STORED_ID)
)
