WITH HIGHVALUEORDERS AS (
    SELECT
        USERID,
        ORDERAMOUNT
    FROM USERORDERS
    WHERE ORDERAMOUNT > 300
)

SELECT
    U.FIRSTNAME,
    U.LASTNAME,
    H.ORDERAMOUNT
FROM USERS AS U
INNER JOIN HIGHVALUEORDERS AS H ON U.USERID = H.USERID;
