--Get the Top 3 Users Who Spent the Most--

SELECT TOP 3
    U.FIRSTNAME,
    U.LASTNAME,
    SUM(O.ORDERAMOUNT) AS TOTALSPENT
FROM USERS AS U
INNER JOIN USERORDERS AS O ON U.USERID = O.USERID
GROUP BY U.FIRSTNAME, U.LASTNAME
ORDER BY TOTALSPENT DESC;
