-- DMS for checking index fragmentation

SELECT
    S.NAME AS 'Schema',
    T.NAME AS 'Table',
    I.NAME AS 'Index',
    DDIPS.AVG_FRAGMENTATION_IN_PERCENT,
    DDIPS.PAGE_COUNT
FROM sys.dm_db_index_physical_stats(DB_ID(), NULL, NULL, NULL, NULL) AS DDIPS
INNER JOIN SYS.TABLES AS T ON DDIPS.OBJECT_ID = T.OBJECT_ID
INNER JOIN SYS.SCHEMAS AS S ON T.SCHEMA_ID = S.SCHEMA_ID
INNER JOIN SYS.INDEXES AS I
    ON
        DDIPS.OBJECT_ID = I.OBJECT_ID
        AND DDIPS.INDEX_ID = I.INDEX_ID
WHERE
    DDIPS.DATABASE_ID = DB_ID()
    AND I.NAME IS NOT NULL
    AND DDIPS.AVG_FRAGMENTATION_IN_PERCENT > 0
ORDER BY DDIPS.AVG_FRAGMENTATION_IN_PERCENT DESC
