SELECT
    FIRSTNAME,
    LASTNAME,
    AMOUNTPAID,
    CASE
        WHEN AMOUNTPAID > 300 THEN 'High'
        WHEN AMOUNTPAID BETWEEN 100 AND 300 THEN 'Medium'
        ELSE 'Low'
    END AS PAYMENTCATEGORY
FROM USERS;
