--Users Who Placed Orders and Have Paid More Than $100--

SELECT
    U.FIRSTNAME,
    U.LASTNAME,
    U.EMAIL,
    SUM(O.ORDERAMOUNT) AS TOTALSPENT
FROM USERS AS U
INNER JOIN USERORDERS AS O ON U.USERID = O.USERID
WHERE U.AMOUNTPAID > 100
GROUP BY U.FIRSTNAME, U.LASTNAME, U.EMAIL;
