--users who spent more than the average amount--

SELECT
    FIRSTNAME,
    LASTNAME,
    SUM(O.ORDERAMOUNT) AS TOTALSPENT
FROM USERS AS U
INNER JOIN USERORDERS AS O ON U.USERID = O.USERID
GROUP BY U.FIRSTNAME, U.LASTNAME
HAVING SUM(O.ORDERAMOUNT) > (SELECT AVG(ORDERAMOUNT) FROM USERORDERS);
