--Get the Total Order Amount for Each User--

SELECT
    U.FIRSTNAME,
    U.LASTNAME,
    SUM(O.ORDERAMOUNT) AS TOTALSPENT
FROM USERS AS U
INNER JOIN USERORDERS AS O ON U.USERID = O.USERID
GROUP BY U.FIRSTNAME, U.LASTNAME;
