name: Initialise Timesheet Migration

on:
  workflow_dispatch:
    inputs:
      DB_script:
        description: 'Path to the DB SQL script'
        required: true
        type: string
      job_script:
        description: 'Path to the Job Schedule SQL script'
        required: true
        type: string

jobs:
  DeployDatabase:
    uses: ./.github/workflows/sql-deploy-template.yml
    with:
      sql_script: ${{ github.event.inputs.DB_script }}
      environment_name: SQLServer
    secrets:
      SQL_SERVER_URL: ${{ secrets.DEV_SQL_SERVER_URL }}
      SQL_USERNAME: ${{ secrets.DEV_SQL_USER }}
      SQL_PASSWORD: ${{ secrets.DEV_SQL_PASSWORD }}
      TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}

  DeploySSISPackage:
    needs: DeployDatabase
    uses: ./.github/workflows/tsql-deploy-package.yml

  DeployScheduledJob:
    needs: DeploySSISPackage
    uses: ./.github/workflows/sql-deploy-template.yml
    with:
      sql_script: ${{ github.event.inputs.job_script }}
      environment_name: Job_Schedule
    secrets:
      SQL_SERVER_URL: ${{ secrets.DEV_SQL_SERVER_URL }}
      SQL_USERNAME: ${{ secrets.DEV_SQL_USER }}
      SQL_PASSWORD: ${{ secrets.DEV_SQL_PASSWORD }}
      TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
      
