name: Teams Notification Trigger

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Notify Teams
        uses: neonidian/teams-notify-build-status@v3
        with:
          webhookUrl: |
            ${{ secrets.TEAMS_INCOMING_WEBHOOK_URL_1 }}
            ${{ secrets.TEAMS_INCOMING_WEBHOOK_URL_2 }}
          title: Pull Request Notification
          titleBackgroundColor: '#0078D7'  # Blue for information
          status: 'Action Required'
          message: >-
            Test message for push to github
        env:
          SHOULD_DISPLAY_ACTOR_LABEL: true
          SHOULD_DISPLAY_VIEW_RUN_BUTTON: true
          SHOULD_DISPLAY_VIEW_COMMIT_BUTTON: true
