services:
  web:
    build: .
    ports:
      - "5432:5432"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file: 
      - ./.env
  db:
      image: postgres:latest
      environment:
        POSTGRES_USER: restapiudemyproject_user
        POSTGRES_PASSWORD: lbKLkyaps6LrJtDHJllzSouefVXjAXwY
        POSTGRES_DB: restapiudemyproject
      volumes:
        - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: