name: SQL DevProd Deployment

on:
  workflow_dispatch:
    inputs:
      sql_script:
        description: 'Path to the SQL script'
        required: true
        type: string

jobs:
  develop-env:
    runs-on: ubuntu-latest
    environment: development  # Tied to the 'development' environment for approval
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install sqlcmd
        run: |
          sudo apt-get update
          sudo apt-get install -y curl gnupg
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
          sudo apt-get update
          sudo apt-get install -y mssql-tools unixodbc-dev
          echo "/opt/mssql-tools/bin" >> $GITHUB_PATH

      - name: Execute SQL Script (Dev)
        env:
          SQL_SERVER_URL: ${{ secrets.DEV_SQL_SERVER_URL }}
          SQL_USERNAME: ${{ secrets.DEV_SQL_USER }}
          SQL_PASSWORD: ${{ secrets.DEV_SQL_PASSWORD }}
        run: |
          sqlcmd -S "$SQL_SERVER_URL" -U "$SQL_USERNAME" -P "$SQL_PASSWORD" -d master -i "${{ github.event.inputs.sql_script }}" -b
          if [ $? -ne 0 ]; then
            echo "Development deployment failed"
            exit 1
          fi
          echo "Development deployment succeeded"

  production-env:
    runs-on: ubuntu-latest
    needs: develop-env  # Wait for dev deployment to succeed
    environment: production  # Tied to the 'production' environment for approval
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install sqlcmd
        run: |
          sudo apt-get update
          sudo apt-get install -y curl gnupg
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
          sudo apt-get update
          sudo apt-get install -y mssql-tools unixodbc-dev
          echo "/opt/mssql-tools/bin" >> $GITHUB_PATH

      - name: Execute SQL Script (Prod)
        env:
          SQL_SERVER_URL: ${{ secrets.PROD_SQL_SERVER_URL }}
          SQL_USERNAME: ${{ secrets.PROD_SQL_USER }}
          SQL_PASSWORD: ${{ secrets.PROD_SQL_PASSWORD }}
        run: |
          sqlcmd -S "$SQL_SERVER_URL" -U "$SQL_USERNAME" -P "$SQL_PASSWORD" -d master -i "${{ github.event.inputs.sql_script }}" -b
          if [ $? -ne 0 ]; then
            echo "Production deployment failed"
            exit 1
          fi
          echo "Production deployment succeeded"
