name: SQL DevProd TempDeployment

on:
  workflow_dispatch:
    inputs:
      sql_script:
        description: 'Path to the SQL script'
        required: true
        type: string

jobs:
  DeveloperEnv:
    uses: ./.github/workflows/sql-deploy-template.yml
    with:
      sql_script: ${{ github.event.inputs.sql_script }}
      environment_name: development
    secrets:
      SQL_SERVER_URL: ${{ secrets.DEV_SQL_SERVER_URL }}
      SQL_USERNAME: ${{ secrets.DEV_SQL_USER }}
      SQL_PASSWORD: ${{ secrets.DEV_SQL_PASSWORD }}


  ProductionEnv:
    needs: deploy-sql-dev
    uses: ./.github/workflows/sql-deploy-template.yml
    with:
      sql_script: ${{ github.event.inputs.sql_script }}
      environment_name: production
    secrets:
      SQL_SERVER_URL: ${{ secrets.PROD_SQL_SERVER_URL }}
      SQL_USERNAME: ${{ secrets.PROD_SQL_USER }}
      SQL_PASSWORD: ${{ secrets.PROD_SQL_PASSWORD }}
      
