name: Auto Create Pull Request

on:
  push:
    branches:
      - main

jobs:
  cancel-push:
    runs-on: ubuntu-latest
    steps:
      - name: Fail Push Attempt
        run: |
          echo "Direct push to 'main' is blocked. Creating a PR instead."
          exit 1

  auto-pr:
    runs-on: ubuntu-latest
    needs: cancel-push
    if: always()  # Ensures this job runs even if 'cancel-push' fails
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Branch Name
        id: branch_name
        run: echo "BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: "Auto PR - ${{ env.BRANCH_NAME }}"
          body: "This pull request was automatically created after pushing to main."
          branch: ${{ env.BRANCH_NAME }}
          base: main
          labels: |
            automated
            needs-review
          reviewers: ${{ github.actor }}
          draft: false
