name: Test Teams Notification

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    
    steps:
      - uses: neonidian/teams-notify-build-status@v3
        with:
          webhookUrl: ${{ secrets.PR_WEBHOOKURL }}   # Secret name is "TEAMS_INCOMING_WEBHOOK_URL"
          message: Workflow run passed !!
