name: Teams notification push

on:
  push:
    branches:
      -Wed1903

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Send notification
      - uses: neonidian/teams-notify-build-status@v3
        with:
          webhookUrl: ${{ secrets.PR_WEBHOOKURL }}   # Secret name is "TEAMS_INCOMING_WEBHOOK_URL"
          message: Workflow run passed !!